{
 "title": "Consensus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L2 block number",
   "type": "timeseries",
   "description": "Number of the latest L2 block persisted in this node's database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "zksync_consensus_storage_block_store_next_persisted_block - 1",
     "legendFormat": "Number"
    }
   ]
  },
  {
   "title": "L2 block rate (blocks/min)",
   "type": "timeseries",
   "description": "Number of L2 blocks persisted in this node's database per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(zksync_consensus_storage_block_store_next_persisted_block[1m])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Gossip TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "network_gossip_inbound_connections",
     "legendFormat": "Inbound"
    },
    {
     "expr": "network_gossip_outbound_connections",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Peers build version",
   "type": "timeseries",
   "description": "Number of peers on each build version",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(build_version) (network_gossip_peers_by_build_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "description": "Data received over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_tcp_received_bytes[1m])",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "description": "Data sent over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(network_tcp_sent_bytes[1m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "RPC latency client",
   "type": "timeseries",
   "description": "Latency of RPC client requests, in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_sum{type=\"client_send_recv\"}[10m])) / sum by(method) (increase(network_rpc_latency_seconds_count{type=\"client_send_recv\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC latency server",
   "type": "timeseries",
   "description": "Latency of RPC server responses, in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_sum{type=\"server_recv_send\"}[$__rate_interval])) / sum by(method) (increase(network_rpc_latency_seconds_count{type=\"server_recv_send\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC rate client",
   "type": "timeseries",
   "description": "Rate of RPC client requests, in requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_count{type=\"client_send_recv\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC rate server",
   "type": "timeseries",
   "description": "Rate of RPC server responses, in requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (increase(network_rpc_latency_seconds_count{type=\"server_recv_send\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block store calls latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(le) (increase(zksync_consensus_storage_persistent_block_store_block_latency_seconds_bucket[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "View number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    { "expr": "consensus_replica_view_number", "legendFormat": "View number" }
   ]
  },
  {
   "title": "Consensus TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "network_consensus_inbound_connections",
     "legendFormat": "Inbound"
    },
    {
     "expr": "network_consensus_outbound_connections",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "View latency",
   "type": "heatmap",
   "description": "Latency of a single view as observed by the replica. Measures from the start of the view until the start of the next.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by(le) (increase(consensus_view_latency_seconds_bucket[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal latency",
   "type": "heatmap",
   "description": "Latency of receiving a proposal as observed by the replica. Measures from the start of the view until we have a verified proposal.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by(le) (increase(consensus_proposal_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit latency",
   "type": "heatmap",
   "description": "Latency of committing to a block as observed by the replica. Measures from the start of the view until we have a commit QC.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum by(le) (increase(consensus_commit_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal payload size",
   "type": "heatmap",
   "description": "Size of the proposed payload in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum by(le) (increase(consensus_proposal_payload_size_bytes_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}